### ISSUE TITLE
Did you receive my email?

### ISSUE THREAD

**Issue by redfast00** [Isaac-Leonard/esp-open-mac-rs#1]
You sent me an email, which I replied to. Did you correctly receive it? I've been dealing with some email deliverability problems, so just wanted to make sure.

**Comment by Isaac-Leonard** [comment]
Hey, yes I recieved it.
Sorry for the late reply, I've been busy with work and other projects but intend to respond in a bit.
I have however updated this repo with the changes you made in your repo.
